In [1]:
import re
import pandas as pd
import numpy as np

In [3]:
filtered_df = pd.read_csv("filtered_news_cat.csv")

In [4]:
filtered_df.head()

,category,headline,authors,link,short_description,date
0,CRIME,25 Years To Life For Man Who Killed Family In ...,NaN,https://www.huffingtonpost.com/entry/nyc-man-s...,NaN,2015-04-14
1,CRIME,Ahmad Khan Rahami's Dad: I Reported My Son To ...,Ryan Grenoble,https://www.huffingtonpost.com/entry/mohammad-...,He later recanted the statement in which he ca...,2016-09-20
2,CRIME,Cops Catch Burglary Suspects Passed Out In Car...,NaN,https://www.huffingtonpost.com/entry/burglars-...,Their SUV was reportedly packed full of loot s...,2016-08-13
3,CRIME,"Unease Grows Between Mayor, NYPD",Simon McCormack,https://www.huffingtonpost.com/entry/nypd-nyc-...,NaN,2014-10-04
4,CRIME,"Man Mailed Dead Skunks, Raccoon To Rival For J...",NaN,https://www.huffingtonpost.com/entry/travis-ta...,"“It’s bizarre, its just hard to believe.”",2016-09-14

# Query 1 
### headline : domestic violence

In [15]:
re_output = filtered_df[filtered_df['headline'].str.contains('domestic violence',regex=True, na=False, case = False)]

In [16]:
re_output

,category,headline,authors,link,short_description,date
106,CRIME,Texas Massacre Suspect Had Previous Domestic V...,Andy Campbell,https://www.huffingtonpost.com/entry/ron-lee-h...,NaN,2014-07-10
540,WORLD NEWS,Reducing Domestic Violence Helps All Of Haiti,"Bjorn Lomborg, ContributorBjorn Lomborg is dir...",https://www.huffingtonpost.com/entry/reducing-...,"Domestic violence is a human rights issue, a p...",2017-06-27
743,POLITICS,Domestic Violence Still Not Grounds For Divorc...,Melissa Jeltsen,https://www.huffingtonpost.com/entry/domestic-...,A Republican lawmaker said a bill allowing dom...,2017-03-02
885,SPORTS,Rutgers Football Star Pleads Not Guilty To Dom...,NaN,https://www.huffingtonpost.com/entry/rutgers-f...,Authorities say he slammed a woman onto concre...,2015-09-16
892,SPORTS,Male-Run Domestic Violence Group Apologizes Fo...,Maxwell Strachan,https://www.huffingtonpost.com/entry/a-call-to...,"""We recognize and accept that male entitlement...",2015-07-30

# Query 2
### headline : movie podcast

In [17]:
re_output_2 = filtered_df[filtered_df['headline'].str.contains('movie podcast',regex=True, na=False, case = False)]

In [18]:
re_output_2

,category,headline,authors,link,short_description,date
232,ENTERTAINMENT,Mighty Movie Podcast: Joe Avella on Master of ...,"Dan Persons, Contributor\nProducer - CFQtv",https://www.huffingtonpost.com/entry/cinefanta...,If you ever wondered whether the people who co...,2013-03-03
258,ENTERTAINMENT,Mighty Movie Podcast: Writer Katie Dippold on ...,"Dan Persons, Contributor\nProducer - CFQtv",https://www.huffingtonpost.com/entry/mighty-mo...,The Heat isn't shy about acknowledging its deb...,2013-06-30
355,ENTERTAINMENT,Mighty Movie Podcast: Pablo Larrain on No,"Dan Persons, Contributor\nProducer - CFQtv",https://www.huffingtonpost.com/entry/mighty-mo...,"No, director Pablo Larrain's slightly fictiona...",2013-02-10

# Query 3
### short_description : mass shooting

In [23]:
re_output_3 = filtered_df[filtered_df['short_description'].str.contains('mass shooting',regex=True, na=False, case = False)]

In [32]:
re_output_3

,category,headline,authors,link,short_description,date
126,CRIME,San Bernardino Police Officer: 'I'll Take A Bu...,Marina Fang,https://www.huffingtonpost.com/entry/san-berna...,The officer was evacuating people from the Inl...,2015-12-03
199,CRIME,Newtown Shooter May Have Had Interest In Pedop...,Willa Frej,https://www.huffingtonpost.com/entry/adam-lanz...,Adam Lanza thought children were being brainwa...,2017-10-25

# Query 4
### short_description:foreign policy

In [35]:
re_output_4 = filtered_df[filtered_df['short_description'].str.contains('foreign policy',regex=True, na=False, case = False)]

In [36]:
re_output_4

,category,headline,authors,link,short_description,date
693,POLITICS,Sunday Roundup,"Arianna Huffington, Contributor",https://www.huffingtonpost.com/entry/sunday-ro...,"This week, Hillary Clinton took on the war aga...",2015-06-07
695,POLITICS,"With North Korea, A Military Option Means Nucl...","Lillyanne Daigle, ContributorNetwork Campaigne...",https://www.huffingtonpost.com/entry/with-nort...,This tense clash between two nuclear-armed and...,2017-04-15

# Query 5
### short_description:fraud

In [37]:
re_output_5 = filtered_df[filtered_df['short_description'].str.contains('fraud',regex=True, na=False, case = False)]

In [38]:
re_output_5

,category,headline,authors,link,short_description,date
7,CRIME,Brother Of San Bernardino Shooter Among 3 Arre...,NaN,https://www.huffingtonpost.com/entry/san-berna...,The three were arrested on charges of federal ...,2016-04-28
38,CRIME,Accused Fake 'Teen Doctor' Malachi Love-Robins...,Dominique Mosbergen,https://www.huffingtonpost.com/entry/malachi-l...,The 18-year-old is accused of defrauding an 86...,2016-03-03
693,POLITICS,Sunday Roundup,"Arianna Huffington, Contributor",https://www.huffingtonpost.com/entry/sunday-ro...,"This week, Hillary Clinton took on the war aga...",2015-06-07
705,POLITICS,North Carolina State Board Of Election Investi...,Julia Craven,https://www.huffingtonpost.com/entry/north-car...,Probably because in-person fraud is highly unl...,2016-11-02